# Generated by Django 5.1 on 2024-08-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('number', models.CharField(max_length=10, null=True)),
                ('class_student', models.CharField(max_length=30, null=True)),
                ('register_number', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
