# Generated by Django 5.1 on 2024-08-26 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Personne',
            new_name='Student',
        ),
        migrations.DeleteModel(
            name='Eleve',
        ),
    ]
