# Generated by Django 5.1 on 2024-08-26 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_birth_date_student_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='birth_date',
        ),
    ]
