# Generated by Django 5.1 on 2024-08-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_student_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='surname',
        ),
        migrations.AddField(
            model_name='student',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
